# Generated by Django 5.2.12 on 2026-03-19 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('telefone', models.CharField(max_length=30, unique=True)),
                ('estabelecimento', models.CharField(default='', max_length=200)),
                ('nicho', models.CharField(choices=[('hamburguer', 'Hambúrguer'), ('pizza', 'Pizza'), ('sobremesa', 'Sobremesa'), ('comida_brasileira', 'Comida Brasileira'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('funcionarios', models.PositiveIntegerField(default=1)),
                ('faturamento_estimado', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('bloqueado', 'Bloqueado'), ('inadimplente', 'Inadimplente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('proxima_cobranca', models.DateField(blank=True, null=True)),
                ('asaas_id', models.CharField(blank=True, max_length=100)),
                ('fichas_geradas_mes', models.PositiveIntegerField(default=0)),
                ('fichas_limite_mes', models.PositiveIntegerField(default=30)),
                ('total_fichas_geradas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Assinante',
                'verbose_name_plural': 'Assinantes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EstadoConversa',
            fields=[
                ('telefone', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('estado', models.CharField(default='inicio', max_length=100)),
                ('dados_temp', models.TextField(default='{}')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='painel.assinante')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('tecnica', 'Ficha Técnica (XLSX)'), ('operacional', 'Ficha Operacional (PDF)'), ('custo_rapido', 'Cálculo de Custo Rápido')], max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_porcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_porcoes', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('arquivo_url', models.CharField(blank=True, max_length=500)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='painel.assinante')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inadimplencia', 'Inadimplência'), ('limite_fichas', 'Limite de Fichas'), ('erro_sistema', 'Erro de Sistema'), ('sem_entender', 'Agente Não Entendeu'), ('novo_assinante', 'Novo Assinante'), ('cancelamento', 'Cancelamento')], max_length=30)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('aviso', 'Aviso'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='painel.assinante')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=200)),
                ('unidade', models.CharField(default='kg', max_length=20)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fc', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('ic', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='painel.assinante')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('telefone', 'nome')},
            },
        ),
    ]
