# Generated by Django 5.2.12 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
