# Generated by Django 5.2.12 on 2026-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_add_cpf_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.TextField(default='', help_text='Quem é a IA, tom de voz e regras críticas de comportamento.', verbose_name='Persona')),
                ('metodologia', models.TextField(default='', help_text='Didática, clareza, eficiência, linguagem acessível e jornada tripla.', verbose_name='Metodologia')),
                ('instrucoes_geracao', models.TextField(default='', help_text='Como gerar cada parte: relatórios, fichas, cálculos matemáticos.', verbose_name='Instruções de Geração')),
                ('formato_saida', models.TextField(default='', help_text='Template esperado na resposta.', verbose_name='Formato de Saída')),
                ('modelo_ia', models.CharField(default='gpt-4o', max_length=50)),
                ('max_tokens', models.IntegerField(default=3000)),
                ('temperatura', models.FloatField(default=0.7)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração IA',
                'verbose_name_plural': 'Configuração IA',
            },
        ),
    ]
