# Generated by Django 5.2.12 on 2026-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_configuracao_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemBot',
            fields=[
                ('chave', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('boas_vindas', 'Boas-vindas'), ('menu', 'Menu Principal'), ('coleta', 'Coleta de Dados'), ('pagamento', 'Pagamento'), ('fichas', 'Fichas Técnicas'), ('operacional', 'Ficha Operacional (PDF)'), ('erros', 'Erros e Alertas'), ('renovacao', 'Renovação'), ('webhook', 'Webhook / Pós-pagamento')], max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField()),
                ('variaveis', models.CharField(blank=True, help_text='Variáveis disponíveis separadas por vírgula', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem do Bot',
                'verbose_name_plural': 'Mensagens do Bot',
                'ordering': ['categoria', 'ordem'],
            },
        ),
    ]
