# Generated by Django 5.2.12 on 2026-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_mensagembot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerdaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes e Proteínas'), ('laticinios', 'Laticínios e Ovos'), ('vegetais', 'Vegetais e Legumes'), ('frutas', 'Frutas'), ('graos', 'Grãos e Cereais'), ('padaria', 'Farinhas e Panificação'), ('oleos_molhos', 'Óleos, Gorduras e Molhos'), ('doces', 'Açúcar e Doces')], max_length=30)),
                ('perda_percentual', models.PositiveIntegerField(default=0, help_text='Percentual de perda (0-100)')),
                ('tipo_perda', models.CharField(choices=[('limpeza', 'Limpeza'), ('cocção', 'Cocção'), ('nenhuma', 'Nenhuma')], default='nenhuma', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perda de Ingrediente',
                'verbose_name_plural': 'Perdas de Ingredientes',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
