# Generated by Django 5.2.12 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_perdaingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdaingrediente',
            name='perda_percentual',
            field=models.IntegerField(default=0, help_text='Positivo=perda, Negativo=ganho. Ex: 30 perde 30%, -200 ganha 200% (triplica)'),
        ),
        migrations.AlterField(
            model_name='perdaingrediente',
            name='tipo_perda',
            field=models.CharField(choices=[('limpeza', 'Limpeza'), ('coccao', 'Cocção'), ('ganho', 'Ganho (absorve água)'), ('nenhuma', 'Nenhuma')], default='nenhuma', max_length=20),
        ),
    ]
