# Generated by Django 5.2.12 on 2026-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_perdaingrediente_intfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor_primeiro_pagamento', models.DecimalField(decimal_places=2, help_text='Valor do primeiro pagamento com cupom', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('usos', models.PositiveIntegerField(default=0, help_text='Quantas vezes foi usado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-criado_em'],
            },
        ),
    ]
