# Generated by Django 5.2.12 on 2026-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_cupom'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.CharField(max_length=200, unique=True)),
                ('evento_tipo', models.CharField(max_length=80)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Processado',
                'verbose_name_plural': 'Webhooks Processados',
            },
        ),
    ]
