# Generated by Django 5.2.12 on 2026-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_webhook_processado'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='payment_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='modelo_ia',
            field=models.CharField(default='gpt-4.1-mini', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='telefone',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['telefone', '-criado_em'], name='idx_conversa_tel_data'),
        ),
    ]
