# Generated by Django 5.2.12 on 2026-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_add_payment_link_id_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='nicho',
            field=models.CharField(choices=[('hamburguer', 'Hambúrguer'), ('pizza', 'Pizza'), ('sobremesa', 'Sobremesa / Confeitaria'), ('acai', 'Açaí'), ('comida_brasileira', 'Comida Brasileira'), ('paes', 'Pães / Padaria'), ('salgado', 'Salgados'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracaoia',
            name='modelo_ia',
            field=models.CharField(default='gpt-4.1', max_length=50),
        ),
    ]
